### ISSUE TITLE
求SNP对应的碱基对序列·

### ISSUE THREAD

**Issue by kuaileyuandi** [YuetongXU/CropGBM_Tutorial-data#3]
请问一下作者可以提供一下SNP所对应的碱基对序列吗

**Comment by YuetongXU** [comment]
抱歉，应导师要求，数据现在还无法公开

**Comment by kuaileyuandi** [comment]
请问一下，你们从400多万SNP碱基对提取32559个碱基对，一个样本大概需要多长时间？提取F1的6210个样本花了多少时间？

**Comment by kuaileyuandi** [comment]
> 抱歉，应导师要求，数据现在还不能公开

一下，你们从4000多万个NP可能对提取了32559个多考虑，有多少样本需要长时间？

**Comment by kuaileyuandi** [comment]
> 抱歉，应导师要求，数据现在还不能公开

请问一下，你们从4000多万个NP可能对提取了32559个多考虑，有多少样本需要长时间？

**Comment by YuetongXU** [comment]
您好，我们从 4000w SNP 中提取 32559 个 SNP 使用的方法是通过 LD、tagSNP 等操作，然后再与已知的商业 SNP 芯片做 overlap 得到的，不是使用 lightGBM 筛选出来的。因为是分步进行，所以总时间没有统计。

**Comment by YuetongXU** [comment]
lightGBM 筛选是在 32559 个 SNP 的基础上进行的筛选，而非 4000w 基础上

**Comment by kuaileyuandi** [comment]
> 你好，从4000w SNP中提取我们32559个SNP使用的方法是通过LD、tagSNP等操作，然后再与已知的商业SNP芯片做重叠得到的，不是使用lightGBM步出来的。因为是分进行，所以总时间没有统计。

你好，目前我有4000W的SNP值，在提取32599SNP值时比较费时。所以想请问一下可以提供32599的SNP值吗？

**Comment by YuetongXU** [comment]
> > 你好，从4000w SNP中提取我们32559个SNP使用的方法是通过LD、tagSNP等操作，然后再与已知的商业SNP芯片做重叠得到的，不是使用lightGBM步出来的。因为是分进行，所以总时间没有统计。
> 
> 你好，目前我有4000W的SNP值，在提取32599SNP值时比较费时。所以想请问一下可以提供32599的SNP值吗？

抱歉，应导师要求，数据现在还无法公开
